// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTu9lC8TWUR3Cl_ICi_5j5P5bxHoUDxZE',
    appId: '1:657835284385:web:0ea0cf0bd018b9a7331de0',
    messagingSenderId: '657835284385',
    projectId: 'fir-test-1-861f9',
    authDomain: 'fir-test-1-861f9.firebaseapp.com',
    storageBucket: 'fir-test-1-861f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBswSpBk62SyupRwhMdJa9nqCsI5DyF3ig',
    appId: '1:657835284385:android:98c5ca8b51335b59331de0',
    messagingSenderId: '657835284385',
    projectId: 'fir-test-1-861f9',
    storageBucket: 'fir-test-1-861f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAREkWaCdelC-e_Csaj-srJKyHkKljFcGw',
    appId: '1:657835284385:ios:f93b1fb248512da5331de0',
    messagingSenderId: '657835284385',
    projectId: 'fir-test-1-861f9',
    storageBucket: 'fir-test-1-861f9.appspot.com',
    iosBundleId: 'com.example.googleLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAREkWaCdelC-e_Csaj-srJKyHkKljFcGw',
    appId: '1:657835284385:ios:f93b1fb248512da5331de0',
    messagingSenderId: '657835284385',
    projectId: 'fir-test-1-861f9',
    storageBucket: 'fir-test-1-861f9.appspot.com',
    iosBundleId: 'com.example.googleLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTu9lC8TWUR3Cl_ICi_5j5P5bxHoUDxZE',
    appId: '1:657835284385:web:71ce3ab6a74abe5f331de0',
    messagingSenderId: '657835284385',
    projectId: 'fir-test-1-861f9',
    authDomain: 'fir-test-1-861f9.firebaseapp.com',
    storageBucket: 'fir-test-1-861f9.appspot.com',
  );
}
